### ISSUE TITLE
What should the ANDROID_HOME env variable be set to?

### ISSUE THREAD

**Issue by UltimateBoi** [wswebcreation/start-android-emulator#14]
title*

**Comment by wswebcreation** [comment]
See https://web.archive.org/web/20180210044548/http://spring.io/guides/gs/android/

**Comment by UltimateBoi** [comment]
I did everything on there and still get this:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync C:\Program Files\commandlinetools-win-8092744_latest\cmdline-tools\emulator\emulator ENOENT
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at execFileSync (node:child_process:858:15)
    at getEmulators (C:\Users\Ultimate\AppData\Roaming\npm\node_modules\start-android-emulator\build\index.js:102:53)
    at C:\Users\Ultimate\AppData\Roaming\npm\node_modules\start-android-emulator\build\index.js:23:21
    at Object.<anonymous> (C:\Users\Ultimate\AppData\Roaming\npm\node_modules\start-android-emulator\build\index.js:48:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawnSync C:\\Program Files\\commandlinetools-win-8092744_latest\\cmdline-tools\\emulator\\emulator',
  path: 'C:\\Program Files\\commandlinetools-win-8092744_latest\\cmdline-tools\\emulator\\emulator',
  spawnargs: [ '-list-avds' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```
